pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -Denforcer.skip=true -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
